# Generated by Django 6.0.5 on 2026-06-05 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_product_category_alter_product_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='discount_status',
            new_name='status',
        ),
    ]
